# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
pandoc: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: 3.3
      brew_packages: libgit2
  allow_failures:
    - os: osx

repos:
  docker: https://r.docker.stat.auckland.ac.nz
  rforge: https://r-forge.r-project.org/

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown -R $(whoami) /usr/local/share; fi

after_success:
  - Rscript -e 'covr::codecov()'
