language: R
sudo: false
cache: packages
latex: false
pandoc: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release
      brew_packages:
        - libgit2
        - rename
  allow_failures:
    - os: osx
    - r: devel

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - _R_CHECK_SYSTEM_CLOCK_=false

repos:
  docker: https://r.docker.stat.auckland.ac.nz

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then sudo chown -R $(whoami) /usr/local/share;
    Rscript -e "install.packages('lazyeval', repos='https://cran.rstudio.com')";
  fi

after_success:
- Rscript -e 'covr::codecov()'
