# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false

matrix:
  include:
    - os: osx
      r: 3.3
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel

repos:
  docker: https://r.docker.stat.auckland.ac.nz
  rforge: https://r-forge.r-project.org/

r_github_packages:
  - tidyverse/readr

after_success:
    - Rscript -e 'covr::codecov()'
