language: R
sudo: false
cache: packages
latex: false
pandoc: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release
      brew_packages: 
        - libgit2
        - rename
  allow_failures:
    - os: osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
    - _R_CHECK_SYSTEM_CLOCK_=FALSE

repos:
  docker: https://r.docker.stat.auckland.ac.nz

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then sudo chown -R $(whoami) /usr/local/share;
    Rscript -e "install.packages('lazyeval', repos='https://cran.rstudio.com')";
  fi

after_success:
- Rscript -e 'covr::codecov()'
# - if [[ "$TRAVIS_BRANCH" == "fake-master" ]];
#     git push --tags;
#   fi

# wget https://raw.githubusercontent.com/iNZightVIT/dev/master/rename_binaries.R -O rename_binaries.R;
# Rscript rename_binaries.R
before_deploy:
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; 
      then R CMD INSTALL --build iNZightTools*.tar.gz; 
      rm -f *.tar.gz; 
    fi
  - wget https://raw.githubusercontent.com/iNZightVIT/dev/master/read_latest_changes.R -O read_latest_changes.R
  - export RELEASE_BODY="$(Rscript read_latest_changes.R)"
  - cp DESCRIPTION PACKAGES
  - R CMD INSTALL .;
  - git config --local user.name = "tmelliott"
  - git config --local user.email = "tomelliottnz@gmail.com"
  - export TRAVIS_TAG=$(Rscript -e "cat(as.character(packageVersion('iNZightTools')))")
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: vnkP+d9MWQCGsyBO7E5IMIz6U9G+sJnjMWfCgaidum6RlW3pn+mE7WaO0ORCCaORUOaTHGcwQ+XefVbFxG+rYTZqR+a75e/MdWu5lnMbdljz6R2mMJijfpW3jGT20JyFJC7TYmccTt5UyVKS+vbVezSvbNfKoYdmM+sKvLP3hvcxxl0QFbhxrXesf/cAj9rhwqOxIbo7JP0ihHf4vBieSzwDhlfRL6945jze+qWX3tG+j3Po/PiBSgks/kCAmjnZrsuLLML3qqa9eUC7NQDOls43Mbdhg7gu2TjHAl+qaJT4gf+U7auX4JANJi69GCgKJ0kvkJio8LcFTfhzmJsHv4nZ1MKGy8Js0zEH4hdE55SHzA39Zm113+2xIyrEQ4+r/VnZJB496q250banSmArTGv23LqLpn04UY0i3maY8iN9eDnm7KGaPNABiZNWkui8Hs6s46W1xIubGieCtqo5k9Bw9g8ht01UB13+7kqkNhjVHEJcQ/QuIV6brfqqwOTSeXIcTbIc0XiVWgVyCJW/7RPZ1CATGCTDgoUpyJPyef+dOdUQAWm9aDefsc/cxpJxwj1ASqvCGVdfu+dXR1OCzGPab+1rcag5pmYkqZe5/Hc9IR9FNtvvxK7Bz/arcsLbVpaX38zAmvbzSjrDT9YRGcVZdZLP4FARcT0nHfowhMA=
  file_glob: true
  file: 
    - iNZightTools_*.t*gz
    - PACKAGES
  name: iNZightTools $TRAVIS_TAG
  overwrite: true
  on:
    branch: fake-master
    repo: iNZightVIT/iNZightTools
