# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false

os:
  - osx

r:
  - 3.3
  - release
  - devel

repos:
  docker: http://r.docker.stat.auckland.ac.nz/R
  rforge: https://r-forge.r-project.org/

r_github_packages:
  - tidyverse/readr

after_success:
    - Rscript -e 'covr::codecov()'
