on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "4.1", cache: 1 }
          - { os: windows-latest, r: "4.2", cache: 1 }
          - { os: windows-latest, r: "release", cache: 1 }
          - { os: macOS-latest, r: "release", cache: 1 }
          - {
              os: ubuntu-20.04,
              r: "release",
              cache: 1,
              rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest",
            }
          - {
              os: ubuntu-20.04,
              r: "devel",
              cache: 1,
              rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest",
            }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_FORCE_SUGGESTS_: false
      _R_CHECK_CRAN_INCOMING_REMOTE_: false

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.os }}-${{ matrix.config.r }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: ${{ matrix.config.cache  }}
          # extra-packages: |
          #   tmelliott/surveyspec@develop,
          #   any::rcmdcheck
          needs: |
            check
          install-pandoc: true

      - uses: r-lib/actions/check-r-package@v2

      # - name: Upload check results
      #   if: failure()
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ${{ runner.os }}-r${{ matrix.config.r }}-results
      #     path: check
