on:
  push:
    branches:
      - dev
      - "release/**"

name: Render

jobs:
  render:
    name: Render
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install some dpendencies and the local package
        run: |
          install.packages(c("remotes", "rmarkdown", "roxygen2", "pkgdown"))
          remotes::install_github("gdemin/expss")
          remotes::install_github("tmelliott/surveyspec@develop")
          remotes::install_local(".", dependencies = TRUE)
        shell: Rscript {0}
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Update Documentation
        run: Rscript -e 'roxygen2::roxygenise()'
      - name: Build Site
        run: Rscript -e 'if (requireNamespace("surveyspec", quietly = TRUE)) pkgdown::build_site()'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add man/figures || echo "No figures to add"
          git add man/*.Rd || echo "No documentation to add"
          git add docs/** || echo "No site changes to add"
          git commit README.md -m 'Re-build README.md' || echo "No changes to commit"
          git commit man/** -m 'Update documentation' || echo "No changes to commit"
          git commit docs/** -m 'Update site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
